language: php

php:
  - 5.3

before_script:
 - cd dev/
 - export CFLAGS="-O2 -fnodelete-null-pointer-checks"
 - sh -c "phpize && ./configure --enable-phalcon && make && sudo make install"
 - echo "extension=phalcon.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
 - cd .. 
 - mysql -uroot -e 'create database phalcon_test charset=utf8 collate=utf8_unicode_ci;'
 - mysql -uroot phalcon_test < unit-tests/schemas/mysql/phalcon_test.sql

script: phpunit --debug -c unit-tests/phpunit.xml

notifications:
  email:
    - andres@phalconphp.com
    - eduar@phalconphp.com
