language: php

php:
  - 5.3

before_script:
 - sudo apt-get install memcached
 - wget http://pecl.php.net/get/memcache-2.2.6.tgz
 - tar -xzf memcache-2.2.6.tgz
 - sh -c "cd memcache-2.2.6 && phpize && ./configure --enable-memcache && make && sudo make install"
 - echo "extension=memcache.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
 - wget http://pecl.php.net/get/apc-3.1.9.tgz
 - tar -xzf apc-3.1.9.tgz
 - sh -c "cd APC-3.1.9 && phpize && ./configure --enable-apc && make && sudo make install"
 - echo "extension=apc.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
 - echo "apc.enable_cli = On" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
 - cd unit-tests/engines/
 - git clone https://github.com/bobthecow/mustache.php.git
 - git clone git://github.com/fabpot/Twig.git
 - cd ../..
 - cd dev/
 - export CFLAGS="-O2 -fno-delete-null-pointer-checks"
 - sh -c "phpize && ./configure --enable-phalcon && make && sudo make install"
 - echo "extension=phalcon.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
 - cd ..
 - mysql -uroot -e 'create database phalcon_test charset=utf8 collate=utf8_unicode_ci;'
 - mysql -uroot phalcon_test < unit-tests/schemas/mysql/phalcon_test.sql

script: phpunit --debug -c unit-tests/phpunit.xml

notifications:
  email:
    - andres@phalconphp.com
    - eduar@phalconphp.com
